*** Settings ***
Library    OperatingSystem
Library    String
Library    Collections

*** Variables ***
${ROOT}                        ${CURDIR}/..
${RESULT_FILE}                 /tmp/audit_result.json
${PLATFORM_REPL}               ${ROOT}/platforms/cortex_m0_nvm.repl
${FIRMWARE_ELF}                ${EMPTY}
${BOOTLOADER_ELF}              ${EMPTY}
${PERIPHERAL_INCLUDES}         ${EMPTY}

# Fuzz state files (generated by audit_bootloader.py).
${REPLICA0_FILE}               ${EMPTY}
${REPLICA1_FILE}               ${EMPTY}
${SLOT_A_VEC_FILE}             ${EMPTY}
${SLOT_B_VEC_FILE}             ${EMPTY}
${SLOT_A_IMAGE_FILE}           ${EMPTY}
${SLOT_B_IMAGE_FILE}           ${EMPTY}

# Fault injection.
${FAULT_AT}                    -1
${FAULT_PHASE}                 slot_copy
${TOTAL_WRITES}                28160
${SCENARIO_ID}                 0

# Pass-through for geometry.
${WRITE_GRANULARITY}           ${EMPTY}
${SLOT_A_BASE}                 ${EMPTY}
${SLOT_B_BASE}                 ${EMPTY}
${SLOT_SIZE}                   ${EMPTY}
${META_BASE_0}                 ${EMPTY}
${META_BASE_1}                 ${EMPTY}
${META_SIZE}                   ${EMPTY}
${BOOTLOADER_ENTRY}            ${EMPTY}
${NVM_CTRL_PATH}               ${EMPTY}
${RUN_DURATION}                ${EMPTY}
${OTA_HEADER_SIZE}             ${EMPTY}
${BOOT_CYCLES}                 ${EMPTY}
${RUNTIME_FAULT_WRITE}         ${EMPTY}

*** Keywords ***
Resolve Path
    [Arguments]    ${path_value}
    ${is_abs}=    Evaluate    os.path.isabs(r'''${path_value}''')    modules=os
    ${resolved}=    Run Keyword If    ${is_abs}
    ...    Set Variable    ${path_value}
    ...    ELSE    Normalize Path    ${ROOT}/${path_value}
    [Return]    ${resolved}

Include Peripheral If Provided
    [Arguments]    ${cs_path}
    ${trimmed}=    Strip String    ${cs_path}
    Run Keyword If    '${trimmed}' == ''    Return From Keyword
    ${resolved_cs}=    Resolve Path    ${trimmed}
    Execute Command    include "${resolved_cs}"

Load ELF If Provided
    [Arguments]    ${elf_path}
    Run Keyword If    '${elf_path}' == '${EMPTY}'    Return From Keyword
    ${resolved_elf}=    Resolve Path    ${elf_path}
    Execute Command    sysbus LoadELF @${resolved_elf}

*** Test Cases ***
Run Audit Point
    Execute Command    $result_file="${RESULT_FILE}"
    Execute Command    $fault_at=${FAULT_AT}
    Execute Command    $fault_phase="${FAULT_PHASE}"
    Execute Command    $total_writes=${TOTAL_WRITES}
    Execute Command    $scenario_id=${SCENARIO_ID}

    # State files.
    Run Keyword If    '${REPLICA0_FILE}' != '${EMPTY}'    Execute Command    $replica0_file="${REPLICA0_FILE}"
    Run Keyword If    '${REPLICA1_FILE}' != '${EMPTY}'    Execute Command    $replica1_file="${REPLICA1_FILE}"
    Run Keyword If    '${SLOT_A_VEC_FILE}' != '${EMPTY}'    Execute Command    $slot_a_vec_file="${SLOT_A_VEC_FILE}"
    Run Keyword If    '${SLOT_B_VEC_FILE}' != '${EMPTY}'    Execute Command    $slot_b_vec_file="${SLOT_B_VEC_FILE}"
    Run Keyword If    '${SLOT_A_IMAGE_FILE}' != '${EMPTY}'
    ...    Execute Command    $slot_a_image_file="${SLOT_A_IMAGE_FILE}"
    Run Keyword If    '${SLOT_B_IMAGE_FILE}' != '${EMPTY}'
    ...    Execute Command    $slot_b_image_file="${SLOT_B_IMAGE_FILE}"

    # Geometry pass-through.
    Run Keyword If    '${WRITE_GRANULARITY}' != '${EMPTY}'    Execute Command    $write_granularity=${WRITE_GRANULARITY}
    Run Keyword If    '${SLOT_A_BASE}' != '${EMPTY}'    Execute Command    $slot_a_base=${SLOT_A_BASE}
    Run Keyword If    '${SLOT_B_BASE}' != '${EMPTY}'    Execute Command    $slot_b_base=${SLOT_B_BASE}
    Run Keyword If    '${SLOT_SIZE}' != '${EMPTY}'    Execute Command    $slot_size=${SLOT_SIZE}
    Run Keyword If    '${META_BASE_0}' != '${EMPTY}'    Execute Command    $meta_base_0=${META_BASE_0}
    Run Keyword If    '${META_BASE_1}' != '${EMPTY}'    Execute Command    $meta_base_1=${META_BASE_1}
    Run Keyword If    '${META_SIZE}' != '${EMPTY}'    Execute Command    $meta_size=${META_SIZE}
    Run Keyword If    '${BOOTLOADER_ENTRY}' != '${EMPTY}'    Execute Command    $bootloader_entry=${BOOTLOADER_ENTRY}
    Run Keyword If    '${NVM_CTRL_PATH}' != '${EMPTY}'    Execute Command    $nvm_ctrl_path="${NVM_CTRL_PATH}"
    Run Keyword If    '${RUN_DURATION}' != '${EMPTY}'    Execute Command    $run_duration="${RUN_DURATION}"
    Run Keyword If    '${OTA_HEADER_SIZE}' != '${EMPTY}'    Execute Command    $ota_header_size=${OTA_HEADER_SIZE}
    Run Keyword If    '${BOOT_CYCLES}' != '${EMPTY}'    Execute Command    $boot_cycles=${BOOT_CYCLES}
    Run Keyword If    '${RUNTIME_FAULT_WRITE}' != '${EMPTY}'    Execute Command    $runtime_fault_write=${RUNTIME_FAULT_WRITE}

    # Load platform + firmware.
    Execute Command    include "${ROOT}/peripherals/NVMemoryController.cs"
    Execute Command    include "${ROOT}/peripherals/GenericNvmController.cs"
    Execute Command    include "${ROOT}/peripherals/TraceReplayEngine.cs"

    @{includes}=    Run Keyword If    '${PERIPHERAL_INCLUDES}' != '${EMPTY}'
    ...    Split String    ${PERIPHERAL_INCLUDES}    ;
    ...    ELSE    Create List
    FOR    ${cs_file}    IN    @{includes}
        Include Peripheral If Provided    ${cs_file}
    END

    ${resolved_platform}=    Resolve Path    ${PLATFORM_REPL}
    Execute Command    mach create
    Execute Command    machine LoadPlatformDescription @${resolved_platform}

    Load ELF If Provided    ${FIRMWARE_ELF}
    Load ELF If Provided    ${BOOTLOADER_ELF}

    ${resolved_script}=    Resolve Path    scripts/run_state_fuzz_audit.resc
    Execute Script    ${resolved_script}

    File Should Exist    ${RESULT_FILE}
